require('mini.ai').setup()
require('mini.align').setup({})
require('mini.comment').setup({})
require('mini.diff').setup({})
require('mini.pairs').setup({})
require('mini.surround').setup({})
require('mini.statusline').setup({})
