{
  imports = [
    ./ags
    ./alacritty.nix
    ./autorandr.nix
    ./bspwm.nix
    ./cursor.nix
    ./direnv.nix
    ./fuzzel.nix
    ./git.nix
    ./hyprland.nix
    ./i3
    ./kubectl.nix
    ./nvim
    ./picom.nix
    ./playerctld.nix
    ./polybar.nix
    ./rofi.nix
    ./rstudio.nix
    ./screenlocker
    ./sxhkd.nix
    ./vscode.nix
    ./zsh.nix
  ];
}
