#!/usr/bin/env bash
# Generate the huurhunter Floating-IP list from Hetzner, and deploy it as an
# untracked data file the nix module reads. hcloud is the source of truth: buy a
# Floating IP assigned to scopecreep, run this, and the list updates. Nothing
# sensitive lands in the (public) repo — the file lives only on the box.
#
# Emits a plain nix list of FIP address strings. The module SNATs the whole
# monitor container to the FIP (uniform across HTTP + browser). With more than one
# FIP it uses the first; host-side rotation is a later concern.
#
# Usage:  ./secrets/huurhunter-fips.sh          # deploy to scopecreep
#         ./secrets/huurhunter-fips.sh --print  # just show the generated nix
set -euo pipefail

SERVER="scopecreep"
REMOTE_PATH="/etc/huurhunter-fips.nix"

server_id=$(hcloud server describe "$SERVER" -o json | jq -r '.id')

# ipv4 FIPs assigned to this server, sorted by address for stable ordering.
# SNAT-to-source is ipv4-only; skip any ipv6 /64 with a warning.
mapfile -t ips < <(
  hcloud floating-ip list -o json \
    | jq -r --argjson sid "$server_id" '
        map(select(.server == $sid and .type == "ipv4"))
        | sort_by(.ip) | .[].ip'
)

if [ "${#ips[@]}" -eq 0 ]; then
  echo "No ipv4 Floating IPs assigned to $SERVER." >&2
  echo "Buy one with: hcloud floating-ip create --type ipv4 --server $SERVER --name huurhunter-egress-1" >&2
fi

# Render the nix data file: a plain list of FIP address strings.
render() {
  echo "# GENERATED by secrets/huurhunter-fips.sh from \`hcloud floating-ip list\`."
  echo "# Do not edit by hand; re-run the script after buying/releasing a FIP."
  echo "["
  for ip in "${ips[@]}"; do
    echo "  \"$ip\""
  done
  echo "]"
}

if [ "${1:-}" = "--print" ]; then
  render
  exit 0
fi

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
render > "$tmpfile"

scp "$tmpfile" "root@$SERVER:$REMOTE_PATH"
ssh "root@$SERVER" "chmod 600 $REMOTE_PATH"
echo "Deployed ${#ips[@]} FIP(s) to $SERVER:$REMOTE_PATH"
echo "Now rebuild the box so the module picks up the pool."
